<?php

namespace app\controller;

use app\middleware\Admin;
use app\model\Chofere;
use app\model\Empresa;
use app\model\Guia;
use app\model\Parametro;
use app\model\Vehiculo;

class DashboardController extends Admin
{
    public string $TITTLE = 'Dashboard';
    public string $MODULO = 'dashboard';

    public int $NUM_TOTAL_GUIAS = 0;
    public int $NUM_TOTAL_CHOFERES = 0;
    public int $NUM_TOTAL_VEHICULOS = 0;
    public int $NUM_TOTAL_EMPRESAS = 0;
    public array $LISTAR_GUIAS = [];
    public string $FORMATO_GUIA_PDF = 'null';
    public int $ID_FORMATO_GUIA = 0;

    public function isAdmin()
    {
        parent::isAdmin(); // TODO: Change the autogenerated stub
        if (!validarPermisos($this->MODULO)) {
            header('location: ' . ROOT_PATH . 'admin\\');
        }
    }

    public function index($actualizar = false): array
    {
        $response = [];
        $modelGuia = new Guia();
        $modelChoferes = new Chofere();
        $modelVehiculos = new Vehiculo();
        $modelEmpresas = new Empresa();

        $this->NUM_TOTAL_GUIAS = formatoMillares($modelGuia->count(1));
        $this->NUM_TOTAL_CHOFERES = formatoMillares($modelChoferes->count(1));
        $this->NUM_TOTAL_VEHICULOS = formatoMillares($modelVehiculos->count(1));
        $this->NUM_TOTAL_EMPRESAS = formatoMillares($modelEmpresas->count(1));

        $formato = getFormato();
        $this->FORMATO_GUIA_PDF = $formato[0];
        $this->ID_FORMATO_GUIA = $formato[1];

        $this->LISTAR_GUIAS = $modelGuia->getAll(1, 'id', 'DESC', '4');

        if ($actualizar){
            $response = crearResponse(
                null,
                true,
                'Vista Actualizada.',
                null,
                'success',
                false
            );

            $response['total_guias'] = $this->NUM_TOTAL_GUIAS;
            $response['total_choferes'] = $this->NUM_TOTAL_CHOFERES;
            $response['total_vehiculos'] = $this->NUM_TOTAL_VEHICULOS;
            $response['total_empresas'] = $this->NUM_TOTAL_EMPRESAS;
            $response['formato'] = $this->FORMATO_GUIA_PDF;

            if (!empty($this->LISTAR_GUIAS)){
                foreach ($this->LISTAR_GUIAS as $guia){
                    $fecha = verFecha($guia['fecha']);
                    $codigo = $guia['codigo'];
                    $destino = $guia['rutas_destino'];
                    $chofer = $guia['choferes_nombre'];
                    $id = $guia['id'];
                    $estatus = $guia['estatus'];
                    $response['listarGuias'][] = array("id" => $id, "fecha" => $fecha, "codigo" => $codigo, "destino" => $destino, "chofer" => $chofer, "estatus" => $estatus);
                }
            }else{
                $response['listarGuias'] = 'guias_vacio';
            }


        }


        return $response;
    }



}